.PHONY: quality test cift-introspection-lint cift-introspection-test cift-release-gate lint format-check typecheck boundaries artifacts

quality: lint format-check typecheck boundaries artifacts cift-introspection-lint cift-introspection-test test

test:
	uv run --extra dev pytest

cift-introspection-test:
	env PYTHONPATH=introspection/src:. uv run --extra dev pytest --no-cov introspection/tests/test_cift_model_training.py introspection/tests/test_cift_paper_mlp.py introspection/tests/test_cift_probe_competition.py introspection/tests/test_cift_probe_head_to_head.py introspection/tests/test_cift_live_probe_competition.py introspection/tests/test_cift_promotion_gate.py introspection/tests/test_cift_promotion_evidence_materializer.py introspection/tests/test_cift_release_gate.py introspection/tests/test_cift_evidence_chain_verifier.py introspection/tests/test_cift_runtime_export.py introspection/tests/test_cift_live_selector_benchmark.py introspection/tests/test_cift_causal_patching.py introspection/tests/test_cift_certification_workflow.py introspection/tests/test_cift_certification_workflow_runner.py introspection/tests/test_cift_feature_ablation.py introspection/tests/test_trained_detector_export.py introspection/tests/test_cift_training_artifact_conversion.py introspection/tests/test_cift_selected_choice_calibration.py introspection/tests/test_cift_selected_choice_sealed_holdout.py

cift-introspection-lint:
	uv run --extra dev ruff check introspection/scripts/ablate_cift_selector_window_features.py introspection/scripts/check_cift_release_gate.py introspection/scripts/compare_cift_probe_head_to_head.py introspection/scripts/convert_cift_training_artifact.py introspection/scripts/materialize_cift_certification_manifest.py introspection/scripts/materialize_cift_live_probe_competition.py introspection/scripts/materialize_cift_promotion_evidence.py introspection/scripts/materialize_selected_choice_calibration.py introspection/scripts/materialize_selected_choice_sealed_holdout.py introspection/scripts/run_cift_certification_workflow.py introspection/scripts/run_cift_counterfactual_patching.py introspection/scripts/run_cift_hidden_state_patching.py introspection/scripts/train_cift_model_bundle.py introspection/scripts/verify_cift_evidence_chain.py introspection/src/aegis_introspection/cift_model_training.py introspection/src/aegis_introspection/cift_causal_patching.py introspection/src/aegis_introspection/cift_certification_workflow.py introspection/src/aegis_introspection/cift_certification_workflow_runner.py introspection/src/aegis_introspection/cift_evidence_chain_verifier.py introspection/src/aegis_introspection/cift_feature_ablation.py introspection/src/aegis_introspection/cift_hidden_state_patching.py introspection/src/aegis_introspection/cift_live_probe_competition.py introspection/src/aegis_introspection/cift_live_selector_benchmark.py introspection/src/aegis_introspection/cift_paper_mlp.py introspection/src/aegis_introspection/cift_probe_competition.py introspection/src/aegis_introspection/cift_probe_head_to_head.py introspection/src/aegis_introspection/cift_promotion_gate.py introspection/src/aegis_introspection/cift_promotion_evidence_materializer.py introspection/src/aegis_introspection/cift_release_gate.py introspection/src/aegis_introspection/cift_runtime_digest.py introspection/src/aegis_introspection/cift_runtime_export.py introspection/src/aegis_introspection/cift_selected_choice_calibration.py introspection/src/aegis_introspection/cift_selected_choice_sealed_holdout.py introspection/src/aegis_introspection/cift_training_artifact_conversion.py introspection/src/aegis_introspection/detector_result_bridge.py introspection/src/aegis_introspection/trained_detector_export.py introspection/tests/test_cift_model_training.py introspection/tests/test_cift_evidence_chain_verifier.py introspection/tests/test_cift_live_probe_competition.py introspection/tests/test_cift_live_selector_benchmark.py introspection/tests/test_cift_causal_patching.py introspection/tests/test_cift_certification_workflow.py introspection/tests/test_cift_certification_workflow_runner.py introspection/tests/test_cift_feature_ablation.py introspection/tests/test_cift_hidden_state_patching.py introspection/tests/test_cift_paper_mlp.py introspection/tests/test_cift_probe_competition.py introspection/tests/test_cift_probe_head_to_head.py introspection/tests/test_cift_promotion_gate.py introspection/tests/test_cift_promotion_evidence_materializer.py introspection/tests/test_cift_release_gate.py introspection/tests/test_cift_runtime_export.py introspection/tests/test_trained_detector_export.py introspection/tests/test_cift_training_artifact_conversion.py introspection/tests/test_cift_selected_choice_calibration.py introspection/tests/test_cift_selected_choice_sealed_holdout.py
	uv run --extra dev ruff format --check introspection/scripts/ablate_cift_selector_window_features.py introspection/scripts/check_cift_release_gate.py introspection/scripts/compare_cift_probe_head_to_head.py introspection/scripts/convert_cift_training_artifact.py introspection/scripts/materialize_cift_certification_manifest.py introspection/scripts/materialize_cift_live_probe_competition.py introspection/scripts/materialize_cift_promotion_evidence.py introspection/scripts/materialize_selected_choice_calibration.py introspection/scripts/materialize_selected_choice_sealed_holdout.py introspection/scripts/run_cift_certification_workflow.py introspection/scripts/run_cift_counterfactual_patching.py introspection/scripts/run_cift_hidden_state_patching.py introspection/scripts/train_cift_model_bundle.py introspection/scripts/verify_cift_evidence_chain.py introspection/src/aegis_introspection/cift_model_training.py introspection/src/aegis_introspection/cift_causal_patching.py introspection/src/aegis_introspection/cift_certification_workflow.py introspection/src/aegis_introspection/cift_certification_workflow_runner.py introspection/src/aegis_introspection/cift_evidence_chain_verifier.py introspection/src/aegis_introspection/cift_feature_ablation.py introspection/src/aegis_introspection/cift_hidden_state_patching.py introspection/src/aegis_introspection/cift_live_probe_competition.py introspection/src/aegis_introspection/cift_live_selector_benchmark.py introspection/src/aegis_introspection/cift_paper_mlp.py introspection/src/aegis_introspection/cift_probe_competition.py introspection/src/aegis_introspection/cift_probe_head_to_head.py introspection/src/aegis_introspection/cift_promotion_gate.py introspection/src/aegis_introspection/cift_promotion_evidence_materializer.py introspection/src/aegis_introspection/cift_release_gate.py introspection/src/aegis_introspection/cift_runtime_digest.py introspection/src/aegis_introspection/cift_runtime_export.py introspection/src/aegis_introspection/cift_selected_choice_calibration.py introspection/src/aegis_introspection/cift_selected_choice_sealed_holdout.py introspection/src/aegis_introspection/cift_training_artifact_conversion.py introspection/src/aegis_introspection/detector_result_bridge.py introspection/src/aegis_introspection/trained_detector_export.py introspection/tests/test_cift_model_training.py introspection/tests/test_cift_evidence_chain_verifier.py introspection/tests/test_cift_live_probe_competition.py introspection/tests/test_cift_live_selector_benchmark.py introspection/tests/test_cift_causal_patching.py introspection/tests/test_cift_certification_workflow.py introspection/tests/test_cift_certification_workflow_runner.py introspection/tests/test_cift_feature_ablation.py introspection/tests/test_cift_hidden_state_patching.py introspection/tests/test_cift_paper_mlp.py introspection/tests/test_cift_probe_competition.py introspection/tests/test_cift_probe_head_to_head.py introspection/tests/test_cift_promotion_gate.py introspection/tests/test_cift_promotion_evidence_materializer.py introspection/tests/test_cift_release_gate.py introspection/tests/test_cift_runtime_export.py introspection/tests/test_trained_detector_export.py introspection/tests/test_cift_training_artifact_conversion.py introspection/tests/test_cift_selected_choice_calibration.py introspection/tests/test_cift_selected_choice_sealed_holdout.py

cift-release-gate:
ifndef MODEL
	$(error MODEL is required. Usage: make cift-release-gate MODEL=path/to/runtime.json DEVICE=mps MANIFEST=path REPORT=path ARTIFACT_ROOT=. MANIFEST_SHA=sha REPORT_SHA=sha READOUT=4)
endif
ifndef DEVICE
	$(error DEVICE is required)
endif
ifndef MANIFEST
	$(error MANIFEST is required)
endif
ifndef REPORT
	$(error REPORT is required)
endif
ifndef ARTIFACT_ROOT
	$(error ARTIFACT_ROOT is required)
endif
ifndef MANIFEST_SHA
	$(error MANIFEST_SHA is required)
endif
ifndef REPORT_SHA
	$(error REPORT_SHA is required)
endif
ifndef READOUT
	$(error READOUT is required)
endif
	env PYTHONPATH=introspection/src:. uv run python introspection/scripts/check_cift_release_gate.py $(MODEL) --repository-root . --required-runtime-prevention-device $(DEVICE) --certification-manifest $(MANIFEST) --certification-report $(REPORT) --certification-artifact-root $(ARTIFACT_ROOT) --certification-manifest-sha256 $(MANIFEST_SHA) --certification-report-sha256 $(REPORT_SHA) --expected-selected-choice-readout-token-count $(READOUT)

lint:
	uv run --extra dev ruff check src/aegis src/detect tests/aegis tests/dp_honey scripts

format-check:
	uv run --extra dev ruff format --check src/aegis src/detect tests/aegis tests/dp_honey scripts

typecheck:
	uv run --extra dev mypy src/aegis src/detect scripts

boundaries:
	uv run python scripts/check_import_boundaries.py

artifacts:
	uv run python scripts/check_artifact_boundaries.py
